--
-- Table structure for table `TransactionTypeMapping`
--
DROP TABLE IF EXISTS `TransactionTypeMapping`;
create table `TransactionTypeMapping` (
  `id`            tinyint unsigned AUTO_INCREMENT primary key,
  `internal_type` enum ('PAID_AMOUNT', 'ADVANCE', 'DISCOUNT_AMOUNT', 'SPENDING_BONUS', 'PROMOTION', 'PROMOTION_WITH_CONDITION', 'COMPENSATION', 'TEST_AMOUNT', 'WITHDRAWAL', 'REFUND', 'SPECIAL_DISCOUNT_AMOUNT', 'MONTHLY_SPENDING_BONUS', 'SPECIAL_SPENDING_BONUS', 'WELCOME_AMOUNT', 'BARTER_AMOUNT', 'MARKETING_AMOUNT') not null,
  `transaction_type`    enum ('COUPON', 'INCOME')                                                                                                                                                                                                                                                                            not null,
  `allow_coupon`  enum ('YES', 'NO') default 'YES'                                                                                                                                    not null,
  `required_interval_spending_days` enum ('YES', 'NO') default 'NO'                                                                                                                   not null,
  `maximum_interval_spending_days`  smallint                                                                                                                                            null,
  `priority`      tinyint unsigned                                                                                                                                                    not null,
  `label`         varchar(128)                                                                                                                                                        not null,
  `is_enabled`    enum('YES', 'NO')                                                                                                                                                   null,
  `comment`       varchar(1024)                                                                                                                                                       null,
  `created_time`  datetime                                                                                                                                                            null,
  `updated_time`  datetime                                                                                                                                                            null
) DEFAULT CHARSET=utf8;

--
-- Dumping data for table `TransactionTypeMapping`
--
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (2, 'PAID_AMOUNT', 'INCOME', 'NO', 'NO', null, 0, 'PAID_AMOUNT', 'YES', 'The real money by clients', '2021-01-01 00:00:00', '2021-01-01 00:00:00');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (5, 'ADVANCE', 'INCOME', 'NO', 'NO', null, 0, 'ADVANCE', 'YES', 'The money by CocCoc. Then based on spending, the clients may enjoy discounts (must be "discounts" or "chiết khấu" in terms of wording) - now manually calculated', '2021-01-01 00:00:00', '2021-01-01 00:00:00');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (8, 'DISCOUNT_AMOUNT', 'COUPON', 'YES', 'NO', 365, 0, 'DISCOUNT_AMOUNT', 'YES', 'Extra money based on 01 transaction PAID_AMOUNT eg: client topup PAID_AMOUNT = 10M --> enjoy DISCOUNT_AMOUNT = 1M. This is kind of our permanent policy for all clients', '2021-01-01 00:00:00', '2021-01-01 00:00:00');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (11, 'SPENDING_BONUS', 'COUPON', 'YES', 'NO', 365, 1, 'SPENDING_BONUS', 'YES', 'Extra money based on spending within a time interval. The bonus is eligible to be activated only when the payment is made', '2021-01-01 00:00:00', '2021-01-01 00:00:00');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (14, 'PROMOTION', 'COUPON', 'YES', 'YES', 365, 2, 'PROMOTION', 'YES', 'Extra money based on promotion campaigns by Sales, that can base on (a) 01 new PAID_AMOUNT within the promotion time. (b) some fixed amount eg 10% discount for ad types. This has expired spending dates', '2021-01-01 00:00:00', '2021-01-01 00:00:00');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (15, 'PROMOTION_WITH_CONDITION', 'COUPON', 'YES', 'YES', 365, 2, 'PROMOTION_WITH_CONDITION', 'YES', 'extra money based on conditions related spending and period of promotion campaign.  Ex: Spending enough 10M from 1st November  to 31 December 2021 → enjoy PROMOTION_WITH_CONDITION 2M. This has expired spending dates, extra_spending_expire_days', '2021-11-17 00:00:00', '2021-11-17 00:00:00');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (17, 'COMPENSATION', 'COUPON', 'YES', 'NO', null, 4, 'COMPENSATION', 'YES', 'Extra money due to our technical/human errors', '2021-01-01 00:00:00', '2021-01-01 00:00:00');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (20, 'TEST_AMOUNT', 'COUPON', 'YES', 'NO', null, 4, 'TEST_AMOUNT', 'YES', 'Extra free money to test new types, features, or internal testing eg QA/Products that are not reported in any minutes or contracts', '2021-01-01 00:00:00', '2021-01-01 00:00:00');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (23, 'REFUND', 'COUPON', 'NO', 'NO', null, 0, 'REFUND', 'YES', 'extra money add to balance due to the system overspending. Auto, daily proccess at night', '2021-01-01 00:00:00', '2021-01-01 00:00:00');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (26, 'SPECIAL_DISCOUNT_AMOUNT', 'COUPON', 'YES', 'NO', null, 0, 'SPECIAL_DISCOUNT_AMOUNT', 'YES', 'extra money based on payment but enjoy special level for special clients (often higher than DISCOUNT_AMOUNT).  This can be VAT or Tax waiving depending on contracts.', '2021-01-01 00:00:00', '2021-01-01 00:00:00');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (29, 'MONTHLY_SPENDING_BONUS', 'COUPON', 'YES', 'NO', 365, 0, 'MONTHLY_SPENDING_BONUS', 'YES', 'extra money based on 01 transaction PAID_AMOUNT eg: client topup PAID_AMOUNT = 10M --> enjoy DISCOUNT_AMOUNT = 1M. This is kind of our permanent policy for all clients', '2021-10-25 14:53:35', '2021-10-25 14:53:40');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (32, 'SPECIAL_SPENDING_BONUS', 'COUPON', 'YES', 'NO', null, 1, 'SPECIAL_SPENDING_BONUS', 'YES', 'similar to SPENDING_BONUS', '2021-10-25 14:55:04', '2021-10-25 14:55:06');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (35, 'WELCOME_AMOUNT', 'COUPON', 'YES', 'NO', null, 0, 'WELCOME_AMOUNT', 'YES', 'extra money for the first paid amount', '2021-10-25 14:56:27', '2021-10-25 14:56:30');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (38, 'BARTER_AMOUNT', 'COUPON', 'YES', 'NO', null, 0, 'BARTER_AMOUNT', 'YES', 'free budget for clients who have a barter contract (bonus)', '2021-10-25 14:57:32', '2021-10-25 14:57:35');
INSERT INTO CoccocAds.TransactionTypeMapping (id, internal_type, transaction_type, allow_coupon, required_interval_spending_days, maximum_interval_spending_days, priority, label, is_enabled, comment, created_time, updated_time) VALUES (41, 'MARKETING_AMOUNT', 'COUPON', 'YES', 'NO', null, 4, 'MARKETING_AMOUNT', 'YES', 'budget for marketing dept.', '2021-10-25 14:58:12', '2021-10-25 14:58:14');