version: "2"

services:
  app_base:
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - COMPOSER_MEMORY_LIMIT=-1
    build:
      dockerfile: Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
        - PHP_OPCACHE_VALIDATE_TIMESTAMPS=${PHP_OPCACHE_VALIDATE_TIMESTAMPS}
        - DOCKER_HOST_IP=${DOCKER_HOST_IP}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - /tmp/docker-xdebug/:/tmp/docker-xdebug/
    cap_add:
      - SYS_ADMIN
